/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_opitz_jni_NativeRCSwitchAdapter */

#ifndef _Included_com_opitz_jni_NativeRCSwitchAdapter
#define _Included_com_opitz_jni_NativeRCSwitchAdapter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_opitz_jni_NativeRCSwitchAdapter
 * Method:    switchOn
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_opitz_jni_NativeRCSwitchAdapter_switchOn
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     com_opitz_jni_NativeRCSwitchAdapter
 * Method:    switchOff
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_com_opitz_jni_NativeRCSwitchAdapter_switchOff
  (JNIEnv *, jobject, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
