package com.opitz.iotprototype

import com.opitz.iotprototype.entities.User;
import java.util.HashSet;

rule "Switch ON roomOne for userOne"
when
   u : User( username == "userOne" )
then
   HashSet<String> specials = new HashSet<String>();
   specials.add( "roomOne" );
   insert( specials );
   System.out.println( "## drools: special rule to switch ON roomOne for userOne ##" );
end

rule "Switch ON roomTwo for userTwo"
when
   u : User( username == "userTwo" )
then
   HashSet<String> specials = new HashSet<String>();
   specials.add( "roomTwo" );
   insert( specials );
   System.out.println( "## drools: special rule to switch ON roomTwo for userTwo ##" );
end

rule "Switch ON roomThree for userThree"
when
   u : User( username == "userThree" )
then
   HashSet<String> specials = new HashSet<String>();
   specials.add( "roomThree" );
   insert( specials );
   System.out.println( "## drools: special rule to switch ON roomThree for userThree ##" );
end

rule "Switch ON roomFour for userFour"
when
   u : User( username == "userFour" )
then
   HashSet<String> specials = new HashSet<String>();
   specials.add( "roomFour" );
   insert( specials );
   System.out.println( "## drools: special rule to switch ON roomFour for userFour ##" );
end

rule "Switch ON roomFive for userFive"
when
   u : User( username == "userFive" )
then
   HashSet<String> specials = new HashSet<String>();
   specials.add( "roomFive" );
   insert( specials );
   System.out.println( "## drools: special rule to switch ON roomFive for userFive ##" );
end