package com.opitz.iotprototype

import com.opitz.iotprototype.entities.User;
import java.util.HashSet;

rule "Switch OFF roomOne for userOne"
when
   u : User( username == "userOne" )
then
   HashSet<String> specials = new HashSet<String>();
   specials.add( "roomOne" );
   insert( specials );
   System.out.println( "## drools: special rule to switch OFF roomOne for userOne ##" );
end

rule "Switch OFF roomTwo for userTwo"
when
   u : User( username == "userTwo" )
then
   HashSet<String> specials = new HashSet<String>();
   specials.add( "roomTwo" );
   insert( specials );
   System.out.println( "## drools: special rule to switch OFF roomTwo for userTwo ##" );
end

rule "Switch OFF roomThree for userThree"
when
   u : User( username == "userThree" )
then
   HashSet<String> specials = new HashSet<String>();
   specials.add( "roomThree" );
   insert( specials );
   System.out.println( "## drools: special rule to switch OFF roomThree for userThree ##" );
end

rule "Switch OFF roomFour for userFour"
when
   u : User( username == "userFour" )
then
   HashSet<String> specials = new HashSet<String>();
   specials.add( "roomFour" );
   insert( specials );
   System.out.println( "## drools: special rule to switch OFF roomFour for userFour ##" );
end

rule "Switch OFF roomFive for userFive"
when
   u : User( username == "userFive" )
then
   HashSet<String> specials = new HashSet<String>();
   specials.add( "roomFive" );
   insert( specials );
   System.out.println( "## drools: special rule to switch OFF roomFive for userFive ##" );
end